### PR TITLE
src: initial knative example

### PR DESCRIPTION
**Pull request by danbev**
This commit's goal is to be able to show how
the Node.js runtime is intended to be used by end users.

### CODE REVIEW

**Comment by danbev** [comment]
@lance Do you think this should be in a repository of its own or perhaps in the faas-js-runtime repository?

**Comment by lance** [comment]
Tough call. Your instinct is right that it probably doesn't belong here (we're also moving away from s2i, so this image might go unused in the future). Maybe it really does deserve its own repo.

**Comment by danbev** [comment]
Should a create one in the openshift-cloud-functions org?

**Comment by lance** [comment]
@danbev sorry I missed your question last week. I think that would be fine.

**Comment by danbev** [comment]
@lance I don't think I can create a repository myself in https://github.com/openshift-cloud-functions. Could you add me as a member or create a repo for me? I was thinking of naming it faas-knative-example or something like that.

**Comment by danbev** [comment]
@lance Would you be able to create a repository for this, or add me to the org and I can do it. Thanks

**Comment by lance** [comment]
@danbev sorry! I have been on PTO but will add you as a contributor to the org now.

**Comment by danbev** [comment]
@lance Great, thanks for that!

**Comment by danbev** [comment]
Closing this PR and I will put this example in:
https://github.com/openshift-cloud-functions/faas-knative-eventing-example.

**Pull request closed without merging**
